services:
  - type: web
    name: hungry-bird
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app

    envVars:
      - key: SECRET_KEY
        value: your_secret_key
      - key: DATABASE_URL
        sync: false  # Render sets this automatically for PostgreSQL add-on
      - key: GOOGLE_MAPS_API_KEY
        value: AIzaSyAN1Y6DgLtlU24YTlp77O2gR_Lw4xiC03w
