"""Add categories column to FoodVendor

Revision ID: b140f437e91b
Revises: 94c214581d86
Create Date: 2025-07-15 23:53:25.603319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b140f437e91b'
down_revision = '94c214581d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_vendor', schema=None) as batch_op:
        batch_op.drop_column('categories')

    # ### end Alembic commands ###
